const FRA = { lat: 50.0379, lon: 8.5622 };
const WORLD = { lat: 0, lon: 0 };
let view = { center: { ...WORLD }, zoom: 1, heading: 0 };
let deviceLocation = null;
let selected = null;
let latestAircraft = [];
let compassEnabled = false;
let compassRequestInFlight = false;
let lastCompassEventTime = 0;
const radar = document.querySelector('#radar');
const map = document.querySelector('#worldMap');
const layer = document.querySelector('#aircraftLayer');
const $ = selector => document.querySelector(selector.startsWith('#') || selector.startsWith('.') ? selector : `#${selector}`);
const clamp = (value, min, max) => Math.min(max, Math.max(min, value));
const normalizeHeading = value => (Number(value || 0) % 360 + 360) % 360;
function cleanFlight(a) { return (a.flight || a.callsign || a.hex || 'UNKNOWN').trim(); }
function aircraftType(a) { const t = (a.t || '').toUpperCase(); if (/^(H|R22|R44|EC|AS|AW|B06|B407|B412)/.test(t)) return 'HELICOPTER'; if (/^(BALL|BALO|BLN|ZEPH)/.test(t)) return 'BALLOON'; if (/^(UAV|RQ|MQ|TB2)/.test(t)) return 'UAV'; if (/^(F16|F15|F18|F22|F35|EUFI|RAFA|GRIP|MIR4|TORN|SU27|MIG)/.test(t)) return 'MILITARY'; return 'COMMERCIAL'; }
function fmtAlt(v) { return typeof v === 'number' ? `${Math.round(v).toLocaleString()} FT` : 'GROUND'; }
function fmtSpeed(v) { return typeof v === 'number' ? `${Math.round(v)} KT` : '—'; }
function fmtHeading(v) { return typeof v === 'number' ? `${Math.round(v).toString().padStart(3, '0')}°` : '—'; }
function distanceNm(a, b) { const r = 3440.069, dLat = (a.lat - b.lat) * Math.PI / 180, dLon = (a.lon - b.lon) * Math.PI / 180; const x = dLon * Math.cos((a.lat + b.lat) * Math.PI / 360); return Math.sqrt(x * x + dLat * dLat) * r; }
function project(lat, lon) { const x = 500 + ((lon - view.center.lon + 540) % 360 - 180) * (1000 / 360) * view.zoom; const y = 250 - (lat - view.center.lat) * (500 / 180) * view.zoom; return { x, y }; }
function drawMap() {
  const grid = []; for (let lon = -180; lon <= 180; lon += 30) grid.push(`<path d="M ${project(85, lon).x} ${project(85, lon).y} L ${project(-85, lon).x} ${project(-85, lon).y}"/>`); for (let lat = -60; lat <= 60; lat += 30) grid.push(`<path d="M ${project(lat, -180).x} ${project(lat, -180).y} L ${project(lat, 180).x} ${project(lat, 180).y}"/>`);
  const continents = [[[-168,72],[-140,70],[-120,55],[-105,50],[-95,25],[-80,10],[-65,15],[-80,35],[-100,45],[-125,55]], [[-82,12],[-65,8],[-52,-5],[-48,-25],[-60,-55],[-75,-40],[-80,-10]], [[-18,35],[10,37],[35,30],[50,10],[42,-20],[20,-35],[5,-5],[-10,10]], [[35,72],[100,70],[145,55],[170,40],[145,25],[105,10],[70,20],[45,40]], [[110,-10],[155,-12],[153,-40],[125,-38],[112,-20]], [[-55,82],[-20,80],[-28,60],[-48,60]]];
  const land = continents.map(points => `<path class="land" d="M ${points.map(([lon, lat]) => { const p = project(lat, lon); return `${p.x} ${p.y}`; }).join(' L ')} Z"/>`).join('');
  map.innerHTML = `<g class="map-grid">${grid.join('')}</g>${land}`;
}
function marker(item, cluster = false) { const p = project(item.lat, item.lon); if (p.x < -100 || p.x > 1100 || p.y < -100 || p.y > 600) return ''; if (cluster) return `<button class="cluster" style="left:${p.x / 10}%;top:${p.y / 5}%" data-lat="${item.lat}" data-lon="${item.lon}" aria-label="${item.count} aircraft clustered here">${item.count}</button>`; const color = aircraftType(item) === 'MILITARY' ? '#ffb34d' : '#ffe14a'; return `<button class="aircraft" style="left:${p.x / 10}%;top:${p.y / 5}%;--rotation:${item.track || 0}deg;--aircraft-color:${color}" data-hex="${item.hex || cleanFlight(item)}" aria-label="Select aircraft ${cleanFlight(item)}"><span class="plane">✦</span><span class="tag">${cleanFlight(item)}</span></button>`; }
function render(payload) { view = { center: payload.center || WORLD, zoom: payload.zoom || 1, heading: payload.heading || 0 }; latestAircraft = payload.aircraft || []; drawMap(); const clusters = (payload.clusters || []).filter(c => c.count > 1 || view.zoom < 4); layer.innerHTML = clusters.map(c => marker(c, true)).join('') + latestAircraft.filter(a => !clusters.some(c => c.count > 1 && c.hexes?.includes(a.hex))).map(a => marker(a)).join(''); $('aircraftCount').textContent = latestAircraft.length || payload.clusters?.reduce((sum, c) => sum + c.count, 0) || 0; $('rangeLabel').textContent = view.zoom < 4 ? 'GLOBAL CLUSTERS' : `ZOOM ${view.zoom}`; $('detailRange').textContent = view.zoom < 4 ? 'GLOBAL' : `LEVEL ${view.zoom}`; $('radarCoordinates').textContent = `${view.center.lat.toFixed(2)}° ${view.center.lat >= 0 ? 'N' : 'S'} / ${Math.abs(view.center.lon).toFixed(2)}° ${view.center.lon >= 0 ? 'E' : 'W'}`; $('northLabel').style.transform = `rotate(${-view.heading}deg)`; renderGeoMarker(); if (selected) { const fresh = latestAircraft.find(a => a.hex === selected.hex); if (fresh) selectAircraft(fresh, false); } }
function selectAircraft(a, scroll = true) { selected = { ...a, hex: a.hex || cleanFlight(a) }; document.querySelectorAll('.aircraft').forEach(el => el.classList.toggle('selected', el.dataset.hex === selected.hex)); $('emptyState').hidden = true; $('aircraftDetails').hidden = false; $('selectionState').textContent = 'TRACKING'; $('detailCallsign').textContent = cleanFlight(a); $('detailAdsbLink').href = `https://adsb.lol/?icao=${encodeURIComponent(selected.hex)}`; $('detailCategory').textContent = aircraftType(a); $('detailAltitude').textContent = fmtAlt(a.alt_baro); $('detailSpeed').textContent = fmtSpeed(a.gs); $('detailHeading').textContent = fmtHeading(a.track); $('detailSquawk').textContent = a.squawk || '—'; $('detailDistance').textContent = `${distanceNm(a, view.center).toFixed(1)} NM`; $('detailPosition').textContent = `${Number(a.lat).toFixed(3)}° · ${Number(a.lon).toFixed(3)}°`; if (scroll && innerWidth < 901) $('.details-panel').scrollIntoView({ behavior: 'smooth', block: 'start' }); }
function renderGeoMarker() { const markerEl = $('geoMarker'); if (!deviceLocation) { markerEl.hidden = true; return; } const p = project(deviceLocation.lat, deviceLocation.lon); markerEl.hidden = p.x < 0 || p.x > 1000 || p.y < 0 || p.y > 500; markerEl.style.left = `${p.x / 10}%`; markerEl.style.top = `${p.y / 5}%`; $('geoStatus').textContent = markerEl.hidden ? 'OUT OF VIEW' : 'GRANTED'; }
async function loadAircraft() { $('mapStatus').textContent = 'Refreshing worldwide aircraft…'; try { const params = new URLSearchParams({ lat: view.center.lat.toFixed(5), lon: view.center.lon.toFixed(5), zoom: view.zoom, heading: view.heading.toFixed(2) }); const response = await fetch(`/api/radar?${params}`, { cache: 'no-store' }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const payload = await response.json(); render(payload); $('connectionLabel').textContent = payload.stale ? 'STALE · ADS-B.LOL' : 'LIVE · ADS-B.LOL'; $('apiStatus').textContent = `${$('aircraftCount').textContent} aircraft indexed · ${new Date(payload.updatedAt || Date.now()).toLocaleTimeString()}`; $('mapStatus').textContent = payload.stale ? 'Showing cached worldwide data' : 'Worldwide aircraft updated'; $('.status-dot').style.background = payload.stale ? 'var(--orange)' : 'var(--green)'; } catch (error) { $('connectionLabel').textContent = 'FEED UNAVAILABLE'; $('mapStatus').textContent = 'Worldwide radar unavailable'; $('apiStatus').textContent = 'Backend radar feed unavailable'; $('.status-dot').style.background = 'var(--orange)'; } $('lastUpdated').textContent = new Date().toLocaleTimeString([], { hour12: false }); }
function setCenter(center) { view.center = { lat: clamp(center.lat, -85, 85), lon: clamp(center.lon, -180, 180) }; loadAircraft(); }
function setZoom(next) { view.zoom = clamp(Math.round(next), 1, 8); render({ center: view.center, heading: view.heading, zoom: view.zoom, aircraft: latestAircraft, clusters: [] }); loadAircraft(); }
function alertGeo(message, status) { $('geoStatus').textContent = status; $('mapStatus').textContent = message; window.alert(message); }
function enableGeolocation() { if (!navigator.geolocation) return alertGeo('Location access is not supported by this browser.', 'UNAVAILABLE'); if (!window.isSecureContext) return alertGeo('Location access requires HTTPS or localhost.', 'UNAVAILABLE'); $('geoBtn').textContent = 'REQUESTING…'; navigator.geolocation.getCurrentPosition(position => { deviceLocation = { lat: position.coords.latitude, lon: position.coords.longitude }; $('geoBtn').textContent = 'LOCATION ACTIVE'; alertGeo('Location access permitted. Centering the radar on you.', 'GRANTED'); setCenter(deviceLocation); }, error => { $('geoBtn').textContent = 'TRY AGAIN'; const denied = error.code === 1; alertGeo(denied ? 'Location access denied. Allow it for this site and try again.' : 'Location could not be determined. Try again.', denied ? 'DENIED' : 'UNAVAILABLE'); }, { enableHighAccuracy: true, maximumAge: 10000, timeout: 15000 }); }
function updateCompassHeading(event) { const now = performance.now(); if (now - lastCompassEventTime < 40) return; let heading; if (Number.isFinite(event.webkitCompassHeading)) heading = event.webkitCompassHeading; else if (Number.isFinite(event.alpha)) heading = 360 - event.alpha + (Number.isFinite(screen.orientation?.angle) ? screen.orientation.angle : 0); if (!Number.isFinite(heading)) return; lastCompassEventTime = now; view.heading = normalizeHeading(heading); $('compassStatus').textContent = `${Math.round(view.heading).toString().padStart(3, '0')}°`; $('compassIndicator').style.setProperty('--compass-heading', `${view.heading}deg`); $('northLabel').style.transform = `rotate(${-view.heading}deg)`; loadAircraft(); }
async function enableCompass() { if (compassEnabled || compassRequestInFlight) return; compassRequestInFlight = true; $('compassBtn').textContent = 'REQUESTING…'; try { if (typeof DeviceOrientationEvent === 'undefined') throw new Error('Compass is unavailable in this browser.'); if (typeof DeviceOrientationEvent.requestPermission === 'function' && await DeviceOrientationEvent.requestPermission() !== 'granted') throw new Error('Compass access denied. Allow motion and orientation access, then try again.'); window.addEventListener('deviceorientation', updateCompassHeading, { passive: true }); window.addEventListener('deviceorientationabsolute', updateCompassHeading, { passive: true }); compassEnabled = true; $('compassBtn').textContent = 'COMPASS ACTIVE'; $('compassStatus').textContent = 'WAITING'; $('compassIndicator').hidden = false; $('mapStatus').textContent = 'Compass active; map orientation follows your device.'; } catch (error) { $('compassBtn').textContent = 'ENABLE COMPASS'; $('compassStatus').textContent = 'DENIED'; alertGeo(error.message, 'DENIED'); } finally { compassRequestInFlight = false; } }
let dragStart = null; radar.addEventListener('wheel', event => { event.preventDefault(); setZoom(view.zoom + (event.deltaY < 0 ? 1 : -1)); }, { passive: false }); radar.addEventListener('pointerdown', event => { dragStart = { x: event.clientX, y: event.clientY, center: { ...view.center } }; radar.setPointerCapture(event.pointerId); }); radar.addEventListener('pointermove', event => { if (!dragStart) return; const rect = radar.getBoundingClientRect(); view.center.lon = dragStart.center.lon - (event.clientX - dragStart.x) / rect.width * 360 / view.zoom; view.center.lat = clamp(dragStart.center.lat + (event.clientY - dragStart.y) / rect.height * 180 / view.zoom, -85, 85); render({ center: view.center, heading: view.heading, zoom: view.zoom, aircraft: latestAircraft, clusters: [] }); }); ['pointerup', 'pointercancel', 'pointerleave'].forEach(type => radar.addEventListener(type, () => { if (dragStart) { dragStart = null; loadAircraft(); } })); layer.addEventListener('click', event => { const aircraft = latestAircraft.find(a => a.hex === event.target.closest('.aircraft')?.dataset.hex); if (aircraft) selectAircraft(aircraft); }); $('zoomIn').addEventListener('click', () => setZoom(view.zoom + 1)); $('zoomOut').addEventListener('click', () => setZoom(view.zoom - 1)); $('refreshBtn').addEventListener('click', loadAircraft); $('geoBtn').addEventListener('click', enableGeolocation); $('compassBtn').addEventListener('click', enableCompass); $('centerBtn').addEventListener('click', () => setCenter(FRA));
async function loadPagesFallback() {
  const points = [[-45,-150],[-45,-30],[-45,90],[0,-90],[0,30],[0,150],[45,-150],[45,-30],[45,90]];
  const results = await Promise.allSettled(points.map(([lat, lon]) => { const upstream = `https://api.adsb.lol/v2/lat/${lat}/lon/${lon}/dist/250`; return fetch(`https://developerlab.dev/api/proxy?url=${encodeURIComponent(upstream)}`).then(response => response.ok ? response.json() : Promise.reject(new Error(`HTTP ${response.status}`))); }));
  const aircraft = []; const seen = new Set(); results.forEach(result => { if (result.status !== 'fulfilled') return; (result.value.ac || []).forEach(item => { const key = String(item.hex || item.flight || `${item.lat}:${item.lon}`).trim().toLowerCase(); if (item.lat != null && item.lon != null && !seen.has(key)) { seen.add(key); aircraft.push({ ...item, hex: key }); } }); });
  const cells = new Map(); aircraft.forEach(item => { const key = `${Math.floor((item.lon + 180) / 18)}:${Math.floor((item.lat + 90) / 9)}`; const cell = cells.get(key) || { lat: 0, lon: 0, count: 0, hexes: [] }; cell.lat += Number(item.lat); cell.lon += Number(item.lon); cell.count += 1; cell.hexes.push(item.hex); cells.set(key, cell); });
  const clusters = [...cells.values()].map(cell => ({ lat: cell.lat / cell.count, lon: cell.lon / cell.count, count: cell.count, hexes: view.zoom >= 4 ? cell.hexes : [] }));
  render({ center: view.center, heading: view.heading, zoom: view.zoom, aircraft: view.zoom >= 4 ? aircraft : [], clusters }); $('connectionLabel').textContent = 'LIVE · ADS-B.LOL'; $('mapStatus').textContent = 'Worldwide aircraft updated via Pages fallback'; $('apiStatus').textContent = `${aircraft.length} aircraft indexed · ${new Date().toLocaleTimeString()}`; $('.status-dot').style.background = 'var(--green)';
}
const backendLoadAircraft = loadAircraft;
loadAircraft = async () => { await backendLoadAircraft(); if ($('mapStatus').textContent === 'Worldwide radar unavailable') { try { await loadPagesFallback(); } catch { $('mapStatus').textContent = 'Worldwide radar unavailable'; } } };
const initialRender = render;
render = payload => { initialRender(payload); radar.style.setProperty('--map-rotation', `${view.heading}deg`); $('rangeLabel').dataset.zoom = view.zoom; };
render({ center: WORLD, zoom: 1, heading: 0, aircraft: [], clusters: [] }); loadAircraft(); setInterval(loadAircraft, 10000);
